import type { Metadata } from 'next';

import Providers from './providers';

import Header from '@/components/layout/Header';
import ServiceWorkerRegister from '@/components/ServiceWorkerRegister';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Providers>
          <ServiceWorkerRegister />
          <Header />
          <main className="container mx-auto px-4 py-16">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
